name: CSharp Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
    
      - name: Install dependencies
        run: dotnet restore
    
      - name: Create a test build
        run: dotnet build --configuration Release
     
      - name: Run Csharp Playwright tests
        run: dotnet test --configuration Release --no-build --logger "html;LogFileName=index.html"
    
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-csharp-results
          path: '**/TestResults'
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-nunit/TestResults
    
    
